name: Docker Image CI

on:
  push:
    branches:
      - 'dev'
      - 'main'
      - 'releases/**'
      - 'features/**'
  workflow_dispatch:

jobs:
  build:
    name: Docker Build & push
    if: ${{github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main' || startsWith(github.ref, 'releases/release')}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.REGISTRY_USERNAME }}/template-generator-ui:${{ github.run_number }}
